version: '1.0'
stages:
  - prepare
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'rajawalk/ubiminimal'
    revision: master
    git: github     
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build
    image_name: rajaubimimial
    working_directory: ./
    tag: 'multi-stage'
    dockerfile: Dockerfile
